services:
  db:
    image: postgres:17
    container_name: notaflow-db
    environment:
      POSTGRES_DB: notaflow
      POSTGRES_USER: notaflow
      POSTGRES_PASSWORD: notaflow
    ports:
      - "5433:5432"
    volumes:
      - notaflow-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: notaflow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: notaflow
      RABBITMQ_DEFAULT_PASS: notaflow

volumes:
  notaflow-data: