### CNPJ com formato certo mas dígito verificador errado (deve dar 400 agora)
POST http://localhost:8080/notas
Content-Type: application/json

{
  "numero": "77774",
  "cnpjEmissor": "11222333000199",
  "dataEmissao": "2026-09-20",
  "valorTotal": 100.00
}

### CNPJ válido de verdade (deve dar 201)
POST http://localhost:8080/notas
Content-Type: application/json

{
  "numero": "88889",
  "cnpjEmissor": "11222333000181",
  "dataEmissao": "2026-09-20",
  "valorTotal": 100.00
}