### Listar com paginação padrão
GET http://localhost:8080/notas

### Listar página específica, tamanho customizado
GET http://localhost:8080/notas?page=0&size=2

### Listar ordenado por valor, crescente
GET http://localhost:8080/notas?sort=valorTotal,asc