spring.application.name=notaflow

spring.datasource.url=jdbc:postgresql://localhost:5433/notaflow
spring.datasource.username=notaflow
spring.datasource.password=notaflow

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
